name: circles-demo

ghc-options: -Wall -freverse-errors

default-extensions:
  - DeriveFunctor
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecursiveDo
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - base
    - cairo
    - clock
    - linear
    - reactive-banana
    - sdl2
    - StateVar
    - text

executables:
  circles-demo:
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - base
      - circles-demo
      - linear
      - reactive-banana
